### ISSUE TITLE
❗[요청] 저희 브랜치가 너무 많습니다.

### ISSUE THREAD

**Issue by peace0096** [Project-Kungeon/JK2#18]
현재 브랜치가 너무 많이 생성되었습니다. 개발이 완료(PR)된( Feature들은 지워주시기 바랍니다.

**Comment by eric1306** [comment]
현재 개발중인 feature/Archor 브랜치 제외하고 제가 생성한 브랜치 삭제했습니다

**Comment by Jo-jaehyeon** [comment]
AssetManager를 제외하고 나머지 제거 완료했습니다.
