### ISSUE TITLE
[PlayerCharacter] ABP Template을 이용한 클래스 animation 및 충돌 판정 기초 완성

### ISSUE THREAD

**Issue by Jo-jaehyeon** [Project-Kungeon/JK2#9]
Animation Blueprint Template을이용해 세부 클래스(Warrior, Assassin, Achor)의 Animation을 구현한다.
완성된 Animation을 기반으로 충돌 판정 기초를 완성한다.

>~~JK2AnimInstance~~
>>~~ABP_JK2PlayerCharacter~~
>>>~~ABP_JK2Assassin~~
>>>~~ABP_JK2Warrior~~
>>>~~ABP_JK2Achor~~

>~~JK2PlayerCharacterAnimNotifyState~~
   
>~~JK2Assassin~~
>~~JK2Warrior~~
>~~JK2Achor~~

**Comment by eric1306** [comment]
@Jo-jaehyeon  JK2Warrior 구현 내용 및 GreyStone Asset 무시를 위한 .gitignore 수정내용 feature/Warrior branch에 Push 완료했습니다.

**Comment by eric1306** [comment]
Archor 완성했습니다. 모든 클래스 구현 완료했으니 이슈 닫겠습니다.
